# Generated by Django 2.2.1 on 2019-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('reporter', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('tech', 'tech')], max_length=50)),
                ('picture', models.ImageField(upload_to='News/')),
                ('audio', models.FileField(upload_to='Audio/')),
            ],
        ),
    ]
