# Generated by Django 2.2.1 on 2019-07-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190722_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='Audio/'),
        ),
    ]
