# Generated by Django 2.2.1 on 2019-07-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190722_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('arts', 'Arts/Culture'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('fashion', 'Fashion'), ('health', 'Health'), ('politics', 'Politics'), ('sport', 'Sport'), ('tech', 'Tech')], max_length=50),
        ),
    ]
