# Generated by Django 2.2.1 on 2019-08-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190725_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(max_length=500)),
                ('video_picture', models.ImageField(upload_to='Videos_Pic/')),
            ],
        ),
    ]
