# Generated by Django 2.2.1 on 2019-08-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_featuredvideos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturedVideos',
            new_name='FeaturedVideo',
        ),
    ]
