# Generated by Django 2.2.1 on 2019-08-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190801_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredvideo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
