# Generated by Django 2.2.1 on 2019-08-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_featuredvideo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='most_popular',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
