# Generated by Django 2.2.1 on 2019-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_news_most_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnapprovedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('reporter', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('arts', 'Arts/Culture'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('fashion', 'Fashion'), ('health', 'Health'), ('politics', 'Politics'), ('sport', 'Sport'), ('tech', 'Tech')], max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
