# Generated by Django 2.2.1 on 2019-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_unapprovednews_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unapprovednews',
            name='picture',
            field=models.ImageField(null=True, upload_to='Unapproved/'),
        ),
    ]
