# Generated by Django 2.2.1 on 2019-08-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190804_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unapprovednews',
            name='category',
            field=models.CharField(choices=[('arts', 'Arts/Culture'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('fashion', 'Fashion'), ('health', 'Health'), ('politics', 'Politics'), ('sport', 'Sport'), ('tech', 'Tech')], default='Arts/Culture', max_length=50),
        ),
    ]
